/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ClienteDAO;
import Modelo.Cliente;
import Modelo.ClienteServicio;
import Modelo.Servicio;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juand
 */
public class VentaDatos extends javax.swing.JFrame {

    /**
     * Creates new form VentaDatos
     */
    public VentaDatos() {
        initComponents();
        cargarDatosTabla();
        // Asegura que solo se cierre la ventanaDatos
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); 
    }

    public void cargarDatosTabla() {
        DefaultTableModel modelo = (DefaultTableModel) jTDatos.getModel();
        modelo.setRowCount(0);

        //LLAMAMOS METODO SELECT DE CLIENTEDAO
        ClienteDAO clienteDAO = new ClienteDAO();
        
        List<ClienteServicio> listaClienteServicios = clienteDAO.SelectClientes();
        for (ClienteServicio clienteServicio : listaClienteServicios) {
            Cliente cliente= clienteServicio.getCliente();
            Servicio servicio = clienteServicio.getServicio();
            
            
            Object[] fila = new Object[11];  // 11 columnas en tu tabla
            fila[0] = cliente.getId_cliente();   // Asumiendo que tienes un método getIdCliente
            fila[1] = cliente.getNombre();
            fila[2] = cliente.getApellido();
            fila[3] = cliente.getCedula();
            fila[4] = cliente.getCelular();
            fila[5] = cliente.getDireccion();
            fila[6] = cliente.getMarca();
            fila[7] = cliente.getModelo();
            fila[8] = cliente.getAnio();
            fila[9] = servicio.getServicio();  // Asumiendo que has añadido métodos para estos atributos
            fila[10] = servicio.getDetalle();

            modelo.addRow(fila);  // Añadimos la fila al modelo
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTDatos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTDatos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTDatos.setFont(new java.awt.Font("Hack Nerd Font Propo", 0, 14)); // NOI18N
        jTDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id_cliente", "Nombre", "Apellido", "Cedula", "Celular", "Direccion", "Marca", "Modelo", "Año", "Servicio", "Detalle"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTDatos.setRowHeight(25);
        jTDatos.setRowMargin(10);
        jTDatos.setShowGrid(true);
        jScrollPane1.setViewportView(jTDatos);
        if (jTDatos.getColumnModel().getColumnCount() > 0) {
            jTDatos.getColumnModel().getColumn(0).setMinWidth(40);
            jTDatos.getColumnModel().getColumn(0).setPreferredWidth(40);
            jTDatos.getColumnModel().getColumn(0).setMaxWidth(40);
            jTDatos.getColumnModel().getColumn(8).setMinWidth(60);
            jTDatos.getColumnModel().getColumn(8).setPreferredWidth(60);
            jTDatos.getColumnModel().getColumn(8).setMaxWidth(60);
            jTDatos.getColumnModel().getColumn(9).setMinWidth(100);
            jTDatos.getColumnModel().getColumn(9).setPreferredWidth(150);
            jTDatos.getColumnModel().getColumn(9).setMaxWidth(150);
            jTDatos.getColumnModel().getColumn(10).setMinWidth(200);
            jTDatos.getColumnModel().getColumn(10).setPreferredWidth(200);
            jTDatos.getColumnModel().getColumn(10).setMaxWidth(200);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1379, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTDatos;
    // End of variables declaration//GEN-END:variables
}
