/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ClienteDAO;
import Modelo.Cliente;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author juand
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    //ATRIBUTOS
    private ClienteDAO clienteDAO;
    //private Servicio servicio;

    /**
     * Creates new form VentanaPrincipal
     *
     * @param clienteDAO
     *
     */
    //CONSTRUCTOR
    public VentanaPrincipal(ClienteDAO clienteDAO) {
        initComponents();
        this.clienteDAO = clienteDAO;

    }

    //METODOS 
    //METODO LIMPIAR PANTALLA 
    public void limpiarPantalla() {
        txtNombre.setText("");
        txtApellido.setText("");
        txtCedula.setText("");
        txtCelular.setText("");
        txtDireccion.setText("");
        txtMarcaVehiculo.setText("");
        txtModeloVehiculo.setText("");
        txtAnioVehiculo.setText("");
        cmbServicioAdquirido.setSelectedIndex(0);
        txtDetalles.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbServicioAdquirido = new javax.swing.JComboBox<>();
        btnCancelar = new javax.swing.JButton();
        txtApellido = new javax.swing.JTextField();
        jLDireccion = new javax.swing.JLabel();
        txtModeloVehiculo = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        jLCelular = new javax.swing.JLabel();
        Marca = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        Vehiculo = new javax.swing.JLabel();
        Modelo = new javax.swing.JLabel();
        cmbServicio = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        NombreForm = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jLApellido = new javax.swing.JLabel();
        txtAnioVehiculo = new javax.swing.JTextField();
        txtMarcaVehiculo = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        anio = new javax.swing.JLabel();
        Detalle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDetalles = new javax.swing.JTextArea();
        jLCedula = new javax.swing.JLabel();
        Servicio = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        btnCargarDatos = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.darkGray);

        cmbServicioAdquirido.setBackground(new java.awt.Color(255, 255, 255));
        cmbServicioAdquirido.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        cmbServicioAdquirido.setForeground(new java.awt.Color(0, 0, 0));
        cmbServicioAdquirido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", " Solo Carroceria 3$", " Lavado Express 5$", " Lavado Premium 10$", " Detailing 20$", " " }));
        cmbServicioAdquirido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cmbServicioAdquirido.setFocusable(false);

        btnCancelar.setBackground(new java.awt.Color(153, 153, 153));
        btnCancelar.setFont(new java.awt.Font("Hack Nerd Font", 0, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarMouseExited(evt);
            }
        });
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtApellido.setBackground(new java.awt.Color(255, 255, 255));
        txtApellido.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(0, 0, 0));

        jLDireccion.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLDireccion.setForeground(java.awt.Color.white);
        jLDireccion.setText("Dirección : ");

        txtModeloVehiculo.setBackground(new java.awt.Color(255, 255, 255));
        txtModeloVehiculo.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        txtModeloVehiculo.setForeground(new java.awt.Color(0, 0, 0));

        txtCelular.setBackground(new java.awt.Color(255, 255, 255));
        txtCelular.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        txtCelular.setForeground(new java.awt.Color(0, 0, 0));

        jLCelular.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLCelular.setForeground(java.awt.Color.white);
        jLCelular.setText("Celular  : ");

        Marca.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        Marca.setForeground(java.awt.Color.white);
        Marca.setText("Marca : ");

        txtCedula.setBackground(new java.awt.Color(255, 255, 255));
        txtCedula.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        txtCedula.setForeground(new java.awt.Color(0, 0, 0));

        Vehiculo.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        Vehiculo.setForeground(java.awt.Color.white);
        Vehiculo.setText("Datos Vehículo");

        Modelo.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        Modelo.setForeground(new java.awt.Color(255, 255, 255));
        Modelo.setText("Modelo : ");

        cmbServicio.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        cmbServicio.setForeground(java.awt.Color.white);
        cmbServicio.setText("Servicio : ");

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        NombreForm.setBackground(new java.awt.Color(153, 255, 153));
        NombreForm.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        NombreForm.setForeground(java.awt.Color.white);
        NombreForm.setText("Datos Cliente");

        jlNombre.setBackground(new java.awt.Color(51, 255, 255));
        jlNombre.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jlNombre.setForeground(java.awt.Color.white);
        jlNombre.setText("Nombre : ");

        jLApellido.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLApellido.setForeground(java.awt.Color.white);
        jLApellido.setText("Apellido :");

        txtAnioVehiculo.setBackground(new java.awt.Color(255, 255, 255));
        txtAnioVehiculo.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        txtAnioVehiculo.setForeground(new java.awt.Color(0, 0, 0));

        txtMarcaVehiculo.setBackground(new java.awt.Color(255, 255, 255));
        txtMarcaVehiculo.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        txtMarcaVehiculo.setForeground(new java.awt.Color(0, 0, 0));

        txtDireccion.setBackground(new java.awt.Color(255, 255, 255));
        txtDireccion.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(0, 0, 0));

        btnGuardar.setBackground(new java.awt.Color(153, 153, 153));
        btnGuardar.setFont(new java.awt.Font("Hack Nerd Font", 0, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarMouseExited(evt);
            }
        });
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        anio.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        anio.setForeground(java.awt.Color.white);
        anio.setText("Año : ");

        Detalle.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        Detalle.setForeground(java.awt.Color.white);
        Detalle.setText("Detalles : ");

        txtDetalles.setBackground(new java.awt.Color(255, 255, 255));
        txtDetalles.setColumns(20);
        txtDetalles.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        txtDetalles.setForeground(new java.awt.Color(0, 0, 0));
        txtDetalles.setLineWrap(true);
        txtDetalles.setRows(5);
        jScrollPane1.setViewportView(txtDetalles);

        jLCedula.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLCedula.setForeground(java.awt.Color.white);
        jLCedula.setText("Cédula : ");

        Servicio.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        Servicio.setForeground(java.awt.Color.white);
        Servicio.setText("Servicio");

        titulo.setBackground(new java.awt.Color(102, 102, 102));
        titulo.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText(" AutoClean Pro");
        titulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        titulo.setOpaque(true);

        btnCargarDatos.setBackground(new java.awt.Color(102, 102, 102));
        btnCargarDatos.setFont(new java.awt.Font("Hack Nerd Font Propo", 0, 14)); // NOI18N
        btnCargarDatos.setForeground(new java.awt.Color(255, 255, 255));
        btnCargarDatos.setText("Clientes");
        btnCargarDatos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCargarDatos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCargarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarDatosActionPerformed(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\juand\\Documents\\ITI online Desarollo de Software\\PIC-PROYECTOS-ITI\\Main\\src\\main\\java\\Vista\\logotipo.jpg")); // NOI18N
        jLabel14.setLabelFor(jLabel14);
        jLabel14.setText("jLabel14");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(362, 362, 362)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(NombreForm, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(btnCargarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Detalle, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbServicio)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jlNombre)
                                .addComponent(jLCedula)
                                .addComponent(jLDireccion)
                                .addComponent(Marca))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(anio)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLCelular)
                                    .addComponent(jLApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(Servicio, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtAnioVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtMarcaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Modelo)
                                .addGap(25, 25, 25)
                                .addComponent(txtModeloVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cmbServicioAdquirido, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(Vehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(55, 55, 55)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NombreForm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApellido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlNombre)
                                .addComponent(jLApellido)))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLCedula))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLCelular)
                                .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLDireccion))
                        .addGap(34, 34, 34)
                        .addComponent(Vehiculo)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMarcaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModeloVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Modelo)
                            .addComponent(Marca))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAnioVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(anio))
                        .addGap(30, 30, 30)
                        .addComponent(Servicio)
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbServicioAdquirido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbServicio))
                        .addGap(28, 28, 28)
                        .addComponent(Detalle)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(btnCargarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1075, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //BTN CARGARDATOS - LISTA CLIENTES
    private void btnCargarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarDatosActionPerformed
        // TODO add your handling code here:
        VentanaDatos ventaDatos = new VentanaDatos();
        ventaDatos.setVisible(true);
        ventaDatos.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnCargarDatosActionPerformed

    //btn GUARDAR - INSERT EN TABLA CLIENTE
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        //OBTENER DATOS DEL FORMULARIO
        String nombre = txtNombre.getText();
        String apellido = txtApellido.getText();
        String cedula = txtCedula.getText();
        String celular = txtCelular.getText();
        String direccion = txtDireccion.getText();
        String marcaVehiculo = txtMarcaVehiculo.getText();
        String modeloVehiculo = txtModeloVehiculo.getText();
        int anioVehiculo = Integer.parseInt(txtAnioVehiculo.getText());
        String servicioAdquirido = (String) cmbServicioAdquirido.getSelectedItem();
        String detalle = txtDetalles.getText();

        //Instancia objeto Cliente con los datos obtenidos del form
        Cliente cliente = new Cliente(nombre, apellido, cedula, celular, direccion,
            marcaVehiculo, modeloVehiculo, anioVehiculo,
            servicioAdquirido, detalle);

        clienteDAO.insertarDatos(cliente);
        JOptionPane.showMessageDialog(this, "Datos Gurdados.");
        //METODO LIMPIAR PANTALLA
        limpiarPantalla();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseExited
        // TODO add your handling code here:
        btnGuardar.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_btnGuardarMouseExited

    //HOVER                                  

    private void btnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseEntered
        btnGuardar.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_btnGuardarMouseEntered

    //METODOS EVENTOS BOTONES
    //METODO CANCELAR
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        //METODO PARA LIMPIAR FORMULARIO AL CANCELAR
        limpiarPantalla();
        //MENSAJE CANCELAD
        JOptionPane.showMessageDialog(this, "Cancelado.");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseExited
        // TODO add your handling code here:
        btnCancelar.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_btnCancelarMouseExited

    //HOVER
                                        
    private void btnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseEntered
        btnCancelar.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_btnCancelarMouseEntered




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Detalle;
    private javax.swing.JLabel Marca;
    private javax.swing.JLabel Modelo;
    private javax.swing.JLabel NombreForm;
    private javax.swing.JLabel Servicio;
    private javax.swing.JLabel Vehiculo;
    private javax.swing.JLabel anio;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCargarDatos;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel cmbServicio;
    private javax.swing.JComboBox<String> cmbServicioAdquirido;
    private javax.swing.JLabel jLApellido;
    private javax.swing.JLabel jLCedula;
    private javax.swing.JLabel jLCelular;
    private javax.swing.JLabel jLDireccion;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtAnioVehiculo;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextArea txtDetalles;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtMarcaVehiculo;
    private javax.swing.JTextField txtModeloVehiculo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

}
