/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Cliente;
import Modelo.Servicio;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juand
 */
public class VentanaEdicion extends javax.swing.JFrame {

    //ATRIBUTOS
    private Cliente cliente;
    private Servicio servicio;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtServicio;
    private javax.swing.JTextField txtDetalle;

    //CONSTRUCTOR inicializar ventanaEdicion
    public VentanaEdicion(Cliente cliente, Servicio servicio) {
        this.cliente = cliente;
        this.servicio = servicio;
        initComponents();
        cargarDatos(cliente, servicio);
        mostrarDatosEnTabla();

    }

    //METODOS
    //METODO PARA CARGAR DATOS
    private void cargarDatos(Cliente cliente, Servicio servicio) {
        txtNombre.setText(cliente.getNombre());
        txtApellido.setText(cliente.getApellido());
        txtCedula.setText(cliente.getCedula());
        txtCelular.setText(cliente.getCelular());
        txtDireccion.setText(cliente.getDireccion());
        txtMarca.setText(cliente.getMarca());
        txtModelo.setText(cliente.getModelo());
        txtAnio.setText(String.valueOf(cliente.getAnio()));
        txtServicio.setText(servicio.getServicio());
        txtDetalle.setText(servicio.getDetalle());

    }
    //METODO PARA MOSTRAR LOS DATOS EN LA TABLA
    private void mostrarDatosEnTabla() {
        DefaultTableModel model = (DefaultTableModel) tablaEdicion.getModel();
        model.setRowCount(0); // Limpiar datos actuales

        Object[] rowData = {
            cliente.getId_cliente(),
            cliente.getNombre(),
            cliente.getApellido(),
            cliente.getCedula(),
            cliente.getCelular(),
            cliente.getDireccion(),
            cliente.getMarca(),
            cliente.getModelo(),
            cliente.getAnio(),
            servicio.getServicio(),
            servicio.getDetalle()
        };

        model.addRow(rowData);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtAnio = new javax.swing.JTextField();
        txtServicio = new javax.swing.JTextField();
        txtDetalle = new javax.swing.JTextField();
        tablaEdicion = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaEdicion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id_cliente", "Nombre", "Apellido", "Cedula", "Celular", "Dirección", "Marca", "Modelo", "Año", "Servicio", "Detalle"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaEdicion);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 951, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaEdicion;
    // End of variables declaration//GEN-END:variables
}
